title: SGTAC Workshop 2026
description: August 24–28, 2026, Izola, Slovenia
url: "https://sgtac.github.io"
baseurl: ""

remote_theme: jekyll/minima
minima:
  skin: auto

header_pages:
  - programme.md
  - participants.md
  - venue.md